---
config:
    interval: 60S
    remove_similar_tags: true
    check_missing_files: true

    add_hr_tags: false
    hr_tag_format: "!!HR${time}!!"

    add_hr_categories: true
    hr_category_format: "!!HR${time}!!"
    overwrite_category_for_hr: false

    skip_checking_for_cross_seeding: true
    skip_checking_auto_start: true
    add_skip_checking_tags: true
    skip_checking_tag_format: "SKIP_CHECKING"

    qbittorrent:
        host: 127.0.0.1
        port: 16585
        username: abacker
        password: "132435."

    add_tag_rules:
        add_r_tag: # 为R盘的两个目录添加"R"标签
            enabled: true
            conditions:
                - path:
                    - "regex:^R:\\\\Download\\\\PTing\\\\"
                    - "regex:^R:\\\\Download\\\\ing\\\\"
            actions:
                - add_tags:
                    - "R" # 添加"R"标签
            stop_following_rules_if: never

    trackers:
        HHan:
            domains:
                - tracker.hhanclub.net
            tags:
                - HHan
            U: 5000KiB/s
            D: 0KiB/s
            HR: 3D@70%+12H
            rules:
                - "@add_tag_rules"
        hdfans_org:
            domains:
                - hdfans.org
            tags:
                - HDFans
            U: 0KiB/s
            D: 0KiB/s
            HR: "3D@80%+12H"
            rules:
                - "@add_tag_rules"
        kufirc_com:
            domains:
                - kufirc.com
            tags:
                - Kufirc
            U: 0KiB/s
            D: 0KiB/s
            HR: ""
            rules:
                - "@add_tag_rules"
        pt_btschool_club:
            domains:
                - pt.btschool.club
            tags:
                - BTSchool
            U: 0KiB/s
            D: 0KiB/s
            HR: "20H@80%+12H"
            rules:
                - "@add_tag_rules"
        ptfans_cc:
            domains:
                - ptfans.cc
            tags:
                - PTFans
            U: 0KiB/s
            D: 0KiB/s
            HR: "7D@80%+12H"
            rules:
                - "@add_tag_rules"
        ptzone_xyz:
            domains:
                - ptzone.xyz
            tags:
                - PTZone
            U: 0KiB/s
            D: 0KiB/s
            HR: ""
            rules:
                - "@add_tag_rules"
        tracker_carpt_net:
            domains:
                - tracker.carpt.net
            tags:
                - CarPT
            U: 0KiB/s
            D: 0KiB/s
            HR: "1D@80%+12H"
            rules:
                - "@add_tag_rules"
        tracker_cyanbug_net:
            domains:
                - tracker.cyanbug.net
            tags:
                - CyanBug
            U: 0KiB/s
            D: 0KiB/s
            HR: ""
            rules:
                - "@add_tag_rules"
        tracker_digitalcore_club:
            domains:
                - tracker.digitalcore.club
                - trackerprxy.digitalcore.club
            tags:
                - DigitalCore
            U: 0KiB/s
            D: 0KiB/s
            HR: "5D@80%+12H"
            rules:
                - "@add_tag_rules"
        tracker_hdbao_cc:
            domains:
                - tracker.hdbao.cc
            tags:
                - HDBao
            U: 0KiB/s
            D: 0KiB/s
            HR: ""
            rules:
                - "@add_tag_rules"
        tracker_hdclone_top:
            domains:
                - tracker.hdclone.top
            tags:
                - HDClone
            U: 0KiB/s
            D: 0KiB/s
            HR: ""
            rules:
                - "@add_tag_rules"
        tracker_hdtime_org:
            domains:
                - tracker.hdtime.org
            tags:
                - HDTime
            U: 0KiB/s
            D: 0KiB/s
            HR: ""
            rules:
                - "@add_tag_rules"
        tracker_m_team_cc:
            domains:
                - tracker.m-team.cc
            tags:
                - MTeam
            remove_tags:
                - M-Team
                - M-Team - TP
            U: 0KiB/s
            D: 0KiB/s
            HR: ""
            rules:
                - "@add_tag_rules"
        tracker_novahd_top:
            domains:
                - tracker.novahd.top
            tags:
                - NovaHD
            U: 0KiB/s
            D: 0KiB/s
            HR: ""
            rules:
                - "@add_tag_rules"
        www_tangpt_top:
            domains:
                - www.tangpt.top
            tags:
                - TangPT
            U: 0KiB/s
            D: 0KiB/s
            HR: ""
            rules:
                - "@add_tag_rules"
