"""安装 `commands` wrapper —— 让 `commands run <task>` 真的能敲。

为什么需要它(2026-09-24 实测): `commands run <task>` 一直只是**文档记法**, 真敲时得展开成
`python <skill-dir:commands>/scripts/run.py run <task>`, 而 skill 的安装位置因项目而异 ⇒
执行者每次要先 Glob 定位(实测 4 次调用才敲出第一条命令)。更糟的是**把 wrapper 放进仓库根也没用**:

    Git Bash  : commands probe → command not found   (PATH 里不含 `.`)
    PowerShell: commands probe → CommandNotFoundException (PowerShell 不搜 cwd)
    cmd.exe   : 搜 cwd(唯一例外)

⇒ 只有落到 **PATH 目录**才叫"真正实现"。本脚本两处都写(默认):
  ① 仓库根  —— `./commands`(Git Bash/POSIX) + `commands.cmd`(cmd.exe cwd 优先); 随平台生成, 已 gitignore
  ② PATH 目录(`~/bin` 或 `~/.local/bin`) —— **项目无关**: 从 `$PWD` 向上找 `.commands/`, 任意项目可用

用法:
    python <skill-dir:commands>/scripts/install_wrapper.py            # cwd + PATH 两处都装(幂等)
    python <skill-dir:commands>/scripts/install_wrapper.py --cwd-only # 只装仓库根(零用户级副作用)
    python <skill-dir:commands>/scripts/install_wrapper.py --dry-run  # 只打印要写什么
    python <skill-dir:commands>/scripts/install_wrapper.py --uninstall

安全边界(为什么默认就写、不学 `add` 那样默认 dry-run): 产物是**幂等、可撤销、零破坏**的转发脚本,
每次都要人先跑一遍 dry-run 就成了新的噪音。改文件前只认自己的**标记行**: 目标已存在且不含标记 ⇒
STOP(不覆盖别人的同名文件), 要覆盖得显式 `--force`。
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
from pathlib import Path

MARK = "commands-wrapper"  # 归属标记: 只动带它的文件, 不碰别人的同名文件
POSIX_NAME = "commands"
WIN_NAME = "commands.cmd"

# 引擎候选位置 —— 与 `_config.SKILL_DIR_CANDIDATES` 同序(项目级 → 用户级)
ENGINE_CANDIDATES = (
    "{root}/.agents/skills/commands/scripts/run.py",
    "{root}/.codebuddy/skills/commands/scripts/run.py",
    "$HOME/.workbuddy-ai/skills/commands/scripts/run.py",
    "$HOME/.codebuddy/skills/commands/scripts/run.py",
)

POSIX_BODY = """#!/bin/sh
# {mark}: 由 commands skill 的 install_wrapper.py 生成, 勿手改(重装即覆盖)
# 作用: 定位仓库根与引擎, 原样转发参数 —— 让 `commands run <task>` 真的可敲。
set -e
root=""
dir="$(pwd)"
while [ -n "$dir" ]; do
  if [ -d "$dir/.commands" ]; then root="$dir"; break; fi
  parent="$(dirname "$dir")"
  [ "$parent" = "$dir" ] && break
  dir="$parent"
done
if [ -z "$root" ]; then
  echo "commands: 当前目录不在任何含 .commands/ 的项目里: $(pwd)" >&2
  exit 2
fi

engine=""
for cand in \\
  "$root/.agents/skills/commands/scripts/run.py" \\
  "$root/.codebuddy/skills/commands/scripts/run.py" \\
  "$HOME/.workbuddy-ai/skills/commands/scripts/run.py" \\
  "$HOME/.codebuddy/skills/commands/scripts/run.py"; do
  if [ -f "$cand" ]; then engine="$cand"; break; fi
done
if [ -z "$engine" ]; then
  echo "commands: 找不到引擎 run.py(试过 .agents/ · .codebuddy/ · 用户级)" >&2
  exit 2
fi

# 解释器: 有 uv + pyproject 时走项目环境 —— 包脚本以 sys.executable 执行, 必须是对的那一个
if [ -f "$root/pyproject.toml" ] && command -v uv >/dev/null 2>&1; then
  exec uv run -q python "$engine" "$@"
fi
exec python "$engine" "$@"
"""

# ❗批处理的写法约束(实测踩过): `rem` 行里不出现**引号 / 括号 / 反引号**, 消息不用 `1>&2` ——
# 带这些字符的 rem 版实测**静默退出 2 且无任何输出**(同一份逻辑换成干净 rem 就正常),
# 而 cmd 的解析细节不值得在这里赌; 保持"最小批处理特征集", 能一眼看出它做什么。
# 消息一律 ASCII: cmd 按 OEM 码页(本机 GBK)读批处理, 中文会变 mojibake。
WIN_BODY = """@echo off
rem {mark}: generated by commands skill install_wrapper.py -- do not edit
rem Walk up from cwd looking for a .commands directory, find the engine, forward all args.
setlocal
set "root="
set "dir=%CD%"
:walk
dir /b /ad "%dir%\\.commands" >nul 2>nul
if not errorlevel 1 set "root=%dir%"
if defined root goto found
for %%I in ("%dir%\\..") do set "parent=%%~fI"
if "%parent%"=="%dir%" goto notfound
set "dir=%parent%"
goto walk

:notfound
echo commands: not inside a project containing .commands : %CD%
exit /b 2

:found
set "engine="
if exist "%root%\\.agents\\skills\\commands\\scripts\\run.py" set "engine=%root%\\.agents\\skills\\commands\\scripts\\run.py"
if not defined engine if exist "%root%\\.codebuddy\\skills\\commands\\scripts\\run.py" set "engine=%root%\\.codebuddy\\skills\\commands\\scripts\\run.py"
if not defined engine if exist "%USERPROFILE%\\.workbuddy-ai\\skills\\commands\\scripts\\run.py" set "engine=%USERPROFILE%\\.workbuddy-ai\\skills\\commands\\scripts\\run.py"
if not defined engine if exist "%USERPROFILE%\\.codebuddy\\skills\\commands\\scripts\\run.py" set "engine=%USERPROFILE%\\.codebuddy\\skills\\commands\\scripts\\run.py"
if not defined engine goto noengine
if not exist "%root%\\pyproject.toml" goto plain
where uv >nul 2>nul
if errorlevel 1 goto plain
uv run -q python "%engine%" %*
exit /b %ERRORLEVEL%

:plain
python "%engine%" %*
exit /b %ERRORLEVEL%

:noengine
echo commands: engine run.py not found under %root%
exit /b 2
"""


def bodies(platform_name: str) -> dict[str, str]:
    """平台 → {文件名: 内容} —— 纯函数(便于自测)。

    Windows 两种都给: `commands` 供 Git Bash(`./commands`), `commands.cmd` 供 cmd/PowerShell
    (PATH 目录下按 PATHEXT 解析)。POSIX 只要 `commands`(带执行位)。
    """
    posix = POSIX_BODY.format(mark=MARK)
    if platform_name == "nt":
        return {POSIX_NAME: posix, WIN_NAME: WIN_BODY.format(mark=MARK)}
    return {POSIX_NAME: posix}


def repo_root(start: Path) -> Path | None:
    """从 start 向上找含 `.commands/` 的目录 —— 与 wrapper 运行期同一判据。"""
    cur = start.resolve()
    for node in (cur, *cur.parents):
        if (node / ".commands").is_dir():
            return node
    return None


def norm_path(text: str) -> str:
    """PATH 条目 → 可比较的绝对路径。

    ❗Git Bash 下 `os.environ["PATH"]` 是 **MSYS 风格**(`/c/Users/x/bin`), 而 `Path.home()` 给的是
    `C:\\Users\\x` —— 直接比会**永远不相等**(实测: `~/bin` 明明在 PATH 上, 却被判成"不在 PATH 上")。
    `/usr/bin` 这类 MSYS 内部路径与 Windows 目录不可比, 归一成空串跳过。
    """
    if os.name == "nt":
        drive = re.match(r"^/([A-Za-z])/(.*)$", text)
        if drive:
            text = f"{drive.group(1)}:{os.sep}{drive.group(2)}"
        elif text.startswith("/"):
            return ""
    try:
        return os.path.normcase(str(Path(text).expanduser().resolve()))
    except OSError:
        return ""


def writable(path: Path) -> bool:
    """真实写探测 —— `os.access(W_OK)` 在 Windows 上不可靠(目录上常给假否定)。"""
    probe = path / f".commands-wrapper-probe-{os.getpid()}"
    try:
        probe.write_text("", encoding="utf-8")
    except OSError:
        return False
    probe.unlink(missing_ok=True)
    return True


def path_dir(env: dict[str, str] | None = None) -> tuple[Path | None, str]:
    """挑一个**已在 PATH 上**且可写的目录装"项目无关"那份; 返回 (目录, 说明)。

    "在 PATH 上但目录不存在"很常见(实测 `~/bin` 就是这样) —— 那就建出来, 不另找地方:
    PATH 是用户已经配好的事实, 我们只往里放一个文件。
    """
    env = env if env is not None else os.environ
    norm = {norm_path(p) for p in env.get("PATH", "").split(os.pathsep) if p.strip()}
    norm.discard("")
    candidates = (Path.home() / "bin", Path.home() / ".local" / "bin")
    for cand in candidates:
        if norm_path(str(cand)) not in norm:
            continue
        if not cand.exists():
            try:
                cand.mkdir(parents=True, exist_ok=True)
            except OSError as exc:
                return None, f"{cand} 在 PATH 上但建不出来({exc}) —— 跳过"
            return cand, f"{cand}(在 PATH 上, 本次新建)"
        if writable(cand):
            return cand, f"{cand}(已在 PATH 上)"
        return None, f"{cand} 在 PATH 上但不可写 —— 跳过"
    return None, (" 与 ".join(str(c) for c in candidates) + " 都不在 PATH 上 —— "
                  "跳过; 想 bare 调用就把其中之一加进 PATH 后重跑")


def write_one(path: Path, text: str, dry_run: bool, force: bool) -> str:
    """写一个 wrapper; 返回一行结果。**只动带标记的文件** —— 别人的同名文件一律停手。"""
    if path.exists():
        try:
            current = path.read_text(encoding="utf-8", errors="replace")
        except OSError as exc:
            return f"[STOP] 读不了 {path}: {exc}"
        if current == text:
            return f"= 已是最新: {path}"
        if MARK not in current and not force:
            return (f"[STOP] {path} 已存在且不是本脚本生成的(缺 `{MARK}` 标记)—— "
                    "改个名或删掉它, 或显式加 --force 覆盖")
    if dry_run:
        return f"+ 将写入: {path}"
    path.parent.mkdir(parents=True, exist_ok=True)
    # ❗`.cmd` 必须 CRLF: cmd.exe 按 CRLF 切行, LF 文件会被整段拆错(实测报 "'exist' 不是内部或外部命令")
    path.write_text(text, encoding="utf-8", newline="\r\n" if path.suffix == ".cmd" else "\n")
    if os.name != "nt":
        path.chmod(0o755)  # 执行位: 少了它就只能 `sh ./commands`
    return f"+ 已写入: {path}"


def uninstall(paths: list[Path]) -> list[str]:
    out: list[str] = []
    for path in paths:
        if not path.exists():
            out.append(f"= 不存在: {path}")
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        if MARK not in text:
            out.append(f"[跳过] {path} 不是本脚本生成的")
            continue
        path.unlink()
        out.append(f"- 已删除: {path}")
    return out


def verify(root: Path) -> subprocess.CompletedProcess:
    """跑一次 wrapper(`list`)自证。

    Windows 下**不能直接 exec** 那个 sh 脚本(CreateProcess 不认 shebang, 报 WinError 193),
    得经 cmd 跑 `commands.cmd`; POSIX 直接 exec。
    """
    if os.name == "nt":
        return subprocess.run(
            f'"{root / WIN_NAME}" list',
            cwd=str(root),
            shell=True,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace"
        )
    return subprocess.run(
        [str(root / POSIX_NAME), "list"],
        cwd=str(root),
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--cwd-only", action="store_true", help="只装仓库根(零用户级副作用)")
    parser.add_argument("--dry-run", action="store_true", help="只打印要写什么")
    parser.add_argument("--uninstall", action="store_true", help="删掉本脚本生成的 wrapper")
    parser.add_argument("--force", action="store_true", help="覆盖不带标记的同名文件")
    parser.add_argument("--no-verify", action="store_true", help="跳过装完的自证(list 一次)")
    args = parser.parse_args(argv)

    root = repo_root(Path.cwd())
    if root is None:
        print(f"[STOP] 当前目录不在任何含 .commands/ 的项目里: {Path.cwd()}\n"
              "  先在项目里 cd 到仓库内(wrapper 靠 `.commands/` 定位仓库根)")
        return 1

    files = bodies(os.name)
    cwd_targets = [(root / name, text) for name, text in files.items()]
    path_target = path_dir()
    path_targets = (
        [(path_target[0] / name, text)
         for name, text in files.items()] if path_target[0] is not None and not args.cwd_only else []
    )

    if args.uninstall:
        for line in uninstall([p for p, _ in cwd_targets + path_targets]):
            print(line)
        return 0

    print(f"仓库根: {root}  ·  平台: {'Windows' if os.name == 'nt' else os.name}  ·  "
          f"文件: {', '.join(files)}")
    for path, text in cwd_targets + path_targets:
        print(f"  {write_one(path, text, args.dry_run, args.force)}")
    if not args.cwd_only:
        print(f"  PATH 目录: {path_target[1]}")

    if args.dry_run:
        return 0

    posix = root / POSIX_NAME
    print(f"\n用法: `./{POSIX_NAME} run <task>`(Git Bash/POSIX)")
    if path_targets:
        print(f"      `{POSIX_NAME} run <task>`(cmd/PowerShell —— PATH 那份已装, bare 形式可用)")
    else:
        print(f"      `{POSIX_NAME} run <task>` 需 PATH 目录那份; 本次没装, 用上面的 `./` 形式")
    if not args.no_verify and posix.exists():
        # 自证: 真跑一次 —— wrapper 定位不到引擎时在这里就暴露, 不留到"用的时候才发现"
        proc = verify(root)
        head = next((ln for ln in proc.stdout.splitlines() if ln.strip()), "")
        print(f"自证: wrapper list → rc={proc.returncode} · {head.strip()[:60]}")
        if proc.returncode != 0:
            print((proc.stderr or proc.stdout).strip()[:400])
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
